Map distName={
  "Andhra Pradesh":[
    "Anantapur",
    "Chittoor",
    "East Godavari",
    "Guntur",
    "Krishna",
    "Kurnool",
    "Nellore",
    "Prakasam",
    "Srikakulam",
    "Visakhapatnam",
    "Vizianagaram",
    "West Godavari",
    "YSR Kadapa"
  ],
  "Arunachal Pradesh":[
    "Tawang",
    "West Kameng",
    "East Kameng",
    "Papum Pare",
    "Kurung Kumey",
    "Kra Daadi",
    "Lower Subansiri",
    "Upper Subansiri",
    "West Siang",
    "East Siang",
    "Siang",
    "Upper Siang",
    "Lower Siang",
    "Lower Dibang Valley",
    "Dibang Valley",
    "Anjaw",
    "Lohit",
    "Namsai",
    "Changlang",
    "Tirap",
    "Longding"
  ],
  "Assam":[
    "Baksa",
    "Barpeta",
    "Biswanath",
    "Bongaigaon",
    "Cachar",
    "Charaideo",
    "Chirang",
    "Darrang",
    "Dhemaji",
    "Dhubri",
    "Dibrugarh",
    "Goalpara",
    "Golaghat",
    "Hailakandi",
    "Hojai",
    "Jorhat",
    "Kamrup Metropolitan",
    "Kamrup",
    "Karbi Anglong",
    "Karimganj",
    "Kokrajhar",
    "Lakhimpur",
    "Majuli",
    "Morigaon",
    "Nagaon",
    "Nalbari",
    "Dima Hasao",
    "Sivasagar",
    "Sonitpur",
    "South Salmara-Mankachar",
    "Tinsukia",
    "Udalguri",
    "West Karbi Anglong"
  ],
  "Bihar":[
    "Araria",
    "Arwal",
    "Aurangabad",
    "Banka",
    "Begusarai",
    "Bhagalpur",
    "Bhojpur",
    "Buxar",
    "Darbhanga",
    "East Champaran (Motihari)",
    "Gaya",
    "Gopalganj",
    "Jamui",
    "Jehanabad",
    "Kaimur (Bhabua)",
    "Katihar",
    "Khagaria",
    "Kishanganj",
    "Lakhisarai",
    "Madhepura",
    "Madhubani",
    "Munger (Monghyr)",
    "Muzaffarpur",
    "Nalanda",
    "Nawada",
    "Patna",
    "Purnia (Purnea)",
    "Rohtas",
    "Saharsa",
    "Samastipur",
    "Saran",
    "Sheikhpura",
    "Sheohar",
    "Sitamarhi",
    "Siwan",
    "Supaul",
    "Vaishali",
    "West Champaran"
  ],
  "Dadra and Nagar Haveli (UT)":[
    "Dadra & Nagar Haveli"
  ],
  "Daman and Diu (UT)":[
    "Daman",
    "Diu"
  ],
  "Chandigarh (UT)":[
    "Chandigarh"
  ],
  "Chhattisgarh":[
    "Balod",
    "Baloda Bazar",
    "Balrampur",
    "Bastar",
    "Bemetara",
    "Bijapur",
    "Bilaspur",
    "Dantewada (South Bastar)",
    "Dhamtari",
    "Durg",
    "Gariyaband",
    "Janjgir-Champa",
    "Jashpur",
    "Kabirdham (Kawardha)",
    "Kanker (North Bastar)",
    "Kondagaon",
    "Korba",
    "Korea (Koriya)",
    "Mahasamund",
    "Mungeli",
    "Narayanpur",
    "Raigarh",
    "Raipur",
    "Rajnandgaon",
    "Sukma",
    "Surajpur  ",
    "Surguja"
  ],
  "Delhi (NCT)":[
    "Central Delhi",
    "East Delhi",
    "New Delhi",
    "North Delhi",
    "North East  Delhi",
    "North West  Delhi",
    "Shahdara",
    "South Delhi",
    "South East Delhi",
    "South West  Delhi",
    "West Delhi"
  ],
  "Goa":[
    "North Goa",
    "South Goa"
  ],
  "Gujarat":[
    "Ahmedabad",
    "Amreli",
    "Anand",
    "Aravalli",
    "Banaskantha (Palanpur)",
    "Bharuch",
    "Bhavnagar",
    "Botad",
    "Chhota Udepur",
    "Dahod",
    "Dangs (Ahwa)",
    "Devbhoomi Dwarka",
    "Gandhinagar",
    "Gir Somnath",
    "Jamnagar",
    "Junagadh",
    "Kachchh",
    "Kheda (Nadiad)",
    "Mahisagar",
    "Mehsana",
    "Morbi",
    "Narmada (Rajpipla)",
    "Navsari",
    "Panchmahal (Godhra)",
    "Patan",
    "Porbandar",
    "Rajkot",
    "Sabarkantha (Himmatnagar)",
    "Surat",
    "Surendranagar",
    "Tapi (Vyara)",
    "Vadodara",
    "Valsad"
  ],
  "Haryana":[
    "Ambala",
    "Bhiwani",
    "Charkhi Dadri",
    "Faridabad",
    "Fatehabad",
    "Gurgaon",
    "Hisar",
    "Jhajjar",
    "Jind",
    "Kaithal",
    "Karnal",
    "Kurukshetra",
    "Mahendragarh",
    "Mewat",
    "Palwal",
    "Panchkula",
    "Panipat",
    "Rewari",
    "Rohtak",
    "Sirsa",
    "Sonipat",
    "Yamunanagar"
  ],
  "Himachal Pradesh":[
    "Bilaspur",
    "Chamba",
    "Hamirpur",
    "Kangra",
    "Kinnaur",
    "Kullu",
    "Lahaul &amp; Spiti",
    "Mandi",
    "Shimla",
    "Sirmaur (Sirmour)",
    "Solan",
    "Una"
  ],
  "Jammu and Kashmir":[
    "Anantnag",
    "Bandipore",
    "Baramulla",
    "Budgam",
    "Doda",
    "Ganderbal",
    "Jammu",
    "Kargil",
    "Kathua",
    "Kishtwar",
    "Kulgam",
    "Kupwara",
    "Leh",
    "Poonch",
    "Pulwama",
    "Rajouri",
    "Ramban",
    "Reasi",
    "Samba",
    "Shopian",
    "Srinagar",
    "Udhampur"
  ],
  "Jharkhand":[
    "Bokaro",
    "Chatra",
    "Deoghar",
    "Dhanbad",
    "Dumka",
    "East Singhbhum",
    "Garhwa",
    "Giridih",
    "Godda",
    "Gumla",
    "Hazaribag",
    "Jamtara",
    "Khunti",
    "Koderma",
    "Latehar",
    "Lohardaga",
    "Pakur",
    "Palamu",
    "Ramgarh",
    "Ranchi",
    "Sahibganj",
    "Seraikela-Kharsawan",
    "Simdega",
    "West Singhbhum"
  ],
  "Karnataka":[
    "Bagalkot",
    "Ballari (Bellary)",
    "Belagavi (Belgaum)",
    "Bengaluru (Bangalore) Rural",
    "Bengaluru (Bangalore) Urban",
    "Bidar",
    "Chamarajanagar",
    "Chikballapur",
    "Chikkamagaluru (Chikmagalur)",
    "Chitradurga",
    "Dakshina Kannada",
    "Davangere",
    "Dharwad",
    "Gadag",
    "Hassan",
    "Haveri",
    "Kalaburagi (Gulbarga)",
    "Kodagu",
    "Kolar",
    "Koppal",
    "Mandya",
    "Mysuru (Mysore)",
    "Raichur",
    "Ramanagara",
    "Shivamogga (Shimoga)",
    "Tumakuru (Tumkur)",
    "Udupi",
    "Uttara Kannada (Karwar)",
    "Vijayapura (Bijapur)",
    "Yadgir"
  ],
  "Kerala":[
    "Alappuzha",
    "Ernakulam",
    "Idukki",
    "Kannur",
    "Kasaragod",
    "Kollam",
    "Kottayam",
    "Kozhikode",
    "Malappuram",
    "Palakkad",
    "Pathanamthitta",
    "Thiruvananthapuram",
    "Thrissur",
    "Wayanad"
  ],
  "Lakshadweep (UT)":[
    "Agatti",
    "Amini",
    "Androth",
    "Bithra",
    "Chethlath",
    "Kavaratti",
    "Kadmath",
    "Kalpeni",
    "Kilthan",
    "Minicoy"
  ],
  "Madhya Pradesh":[
    "Agar Malwa",
    "Alirajpur",
    "Anuppur",
    "Ashoknagar",
    "Balaghat",
    "Barwani",
    "Betul",
    "Bhind",
    "Bhopal",
    "Burhanpur",
    "Chhatarpur",
    "Chhindwara",
    "Damoh",
    "Datia",
    "Dewas",
    "Dhar",
    "Dindori",
    "Guna",
    "Gwalior",
    "Harda",
    "Hoshangabad",
    "Indore",
    "Jabalpur",
    "Jhabua",
    "Katni",
    "Khandwa",
    "Khargone",
    "Mandla",
    "Mandsaur",
    "Morena",
    "Narsinghpur",
    "Neemuch",
    "Panna",
    "Raisen",
    "Rajgarh",
    "Ratlam",
    "Rewa",
    "Sagar",
    "Satna",
    "Sehore",
    "Seoni",
    "Shahdol",
    "Shajapur",
    "Sheopur",
    "Shivpuri",
    "Sidhi",
    "Singrauli",
    "Tikamgarh",
    "Ujjain",
    "Umaria",
    "Vidisha"
  ],
  "Maharashtra":[
    "Ahmednagar",
    "Akola",
    "Amravati",
    "Aurangabad",
    "Beed",
    "Bhandara",
    "Buldhana",
    "Chandrapur",
    "Dhule",
    "Gadchiroli",
    "Gondia",
    "Hingoli",
    "Jalgaon",
    "Jalna",
    "Kolhapur",
    "Latur",
    "Mumbai City",
    "Mumbai Suburban",
    "Nagpur",
    "Nanded",
    "Nandurbar",
    "Nashik",
    "Osmanabad",
    "Palghar",
    "Parbhani",
    "Pune",
    "Raigad",
    "Ratnagiri",
    "Sangli",
    "Satara",
    "Sindhudurg",
    "Solapur",
    "Thane",
    "Wardha",
    "Washim",
    "Yavatmal"
  ],
  "Manipur":[
    "Bishnupur",
    "Chandel",
    "Churachandpur",
    "Imphal East",
    "Imphal West",
    "Jiribam",
    "Kakching",
    "Kamjong",
    "Kangpokpi",
    "Noney",
    "Pherzawl",
    "Senapati",
    "Tamenglong",
    "Tengnoupal",
    "Thoubal",
    "Ukhrul"
  ],
  "Meghalaya":[
    "East Garo Hills",
    "East Jaintia Hills",
    "East Khasi Hills",
    "North Garo Hills",
    "Ri Bhoi",
    "South Garo Hills",
    "South West Garo Hills ",
    "South West Khasi Hills",
    "West Garo Hills",
    "West Jaintia Hills",
    "West Khasi Hills"
  ],
  "Mizoram":[
    "Aizawl",
    "Champhai",
    "Kolasib",
    "Lawngtlai",
    "Lunglei",
    "Mamit",
    "Saiha",
    "Serchhip"
  ],
  "Nagaland":[
    "Dimapur",
    "Kiphire",
    "Kohima",
    "Longleng",
    "Mokokchung",
    "Mon",
    "Peren",
    "Phek",
    "Tuensang",
    "Wokha",
    "Zunheboto"
  ],
  "Odisha":[
    "Angul",
    "Balangir",
    "Balasore",
    "Bargarh",
    "Bhadrak",
    "Boudh",
    "Cuttack",
    "Deogarh",
    "Dhenkanal",
    "Gajapati",
    "Ganjam",
    "Jagatsinghapur",
    "Jajpur",
    "Jharsuguda",
    "Kalahandi",
    "Kandhamal",
    "Kendrapara",
    "Kendujhar (Keonjhar)",
    "Khordha",
    "Koraput",
    "Malkangiri",
    "Mayurbhanj",
    "Nabarangpur",
    "Nayagarh",
    "Nuapada",
    "Puri",
    "Rayagada",
    "Sambalpur",
    "Sonepur",
    "Sundargarh"
  ],
  "Puducherry (UT)":[
    "Karaikal",
    "Mahe",
    "Pondicherry",
    "Yanam"
  ],
  "Punjab":[
    "Amritsar",
    "Barnala",
    "Bathinda",
    "Faridkot",
    "Fatehgarh Sahib",
    "Fazilka",
    "Ferozepur",
    "Gurdaspur",
    "Hoshiarpur",
    "Jalandhar",
    "Kapurthala",
    "Ludhiana",
    "Mansa",
    "Moga",
    "Muktsar",
    "Nawanshahr (Shahid Bhagat Singh Nagar)",
    "Pathankot",
    "Patiala",
    "Rupnagar",
    "Sahibzada Ajit Singh Nagar (Mohali)",
    "Sangrur",
    "Tarn Taran"
  ],
  "Telangana":[
    "Adilabad",
    "Bhadradri Kothagudem",
    "Hyderabad",
    "Jagtial",
    "Jangaon",
    "Jayashankar Bhoopalpally",
    "Jogulamba Gadwal",
    "Kamareddy",
    "Karimnagar",
    "Khammam",
    "Komaram Bheem Asifabad",
    "Mahabubabad",
    "Mahabubnagar",
    "Mancherial",
    "Medak",
    "Medchal",
    "Nagarkurnool",
    "Nalgonda",
    "Nirmal",
    "Nizamabad",
    "Peddapalli",
    "Rajanna Sircilla",
    "Rangareddy",
    "Sangareddy",
    "Siddipet",
    "Suryapet",
    "Vikarabad",
    "Wanaparthy",
    "Warangal (Rural)",
    "Warangal (Urban)",
    "Yadadri Bhuvanagiri"
  ],
  "Tamil Nadu":[
    "Ariyalur",
    "Chennai",
    "Coimbatore",
    "Cuddalore",
    "Dharmapuri",
    "Dindigul",
    "Erode",
    "Kanchipuram",
    "Kanyakumari",
    "Karur",
    "Krishnagiri",
    "Madurai",
    "Nagapattinam",
    "Namakkal",
    "Nilgiris",
    "Perambalur",
    "Pudukkottai",
    "Ramanathapuram",
    "Salem",
    "Sivaganga",
    "Thanjavur",
    "Theni",
    "Thoothukudi (Tuticorin)",
    "Tiruchirappalli",
    "Tirunelveli",
    "Tiruppur",
    "Tiruvallur",
    "Tiruvannamalai",
    "Tiruvarur",
    "Vellore",
    "Viluppuram",
    "Virudhunagar"
  ],
  "Tripura":[
    "Dhalai",
    "Gomati",
    "Khowai",
    "North Tripura",
    "Sepahijala",
    "South Tripura",
    "Unakoti",
    "West Tripura"
  ],
  "Rajasthan":[
    "Ajmer",
    "Alwar",
    "Banswara",
    "Baran",
    "Barmer",
    "Bharatpur",
    "Bhilwara",
    "Bikaner",
    "Bundi",
    "Chittorgarh",
    "Churu",
    "Dausa",
    "Dholpur",
    "Dungarpur",
    "Hanumangarh",
    "Jaipur",
    "Jaisalmer",
    "Jalore",
    "Jhalawar",
    "Jhunjhunu",
    "Jodhpur",
    "Karauli",
    "Kota",
    "Nagaur",
    "Pali",
    "Pratapgarh",
    "Rajsamand",
    "Sawai Madhopur",
    "Sikar",
    "Sirohi",
    "Sri Ganganagar",
    "Tonk",
    "Udaipur"
  ],
  "Sikkim":[
    "East Sikkim",
    "North Sikkim",
    "South Sikkim",
    "West Sikkim"
  ],
  "Uttarakhand":[
    "Almora",
    "Bageshwar",
    "Chamoli",
    "Champawat",
    "Dehradun",
    "Haridwar",
    "Nainital",
    "Pauri Garhwal",
    "Pithoragarh",
    "Rudraprayag",
    "Tehri Garhwal",
    "Udham Singh Nagar",
    "Uttarkashi"
  ],
  "Uttar Pradesh":[
    "Agra",
    "Aligarh",
    "Allahabad",
    "Ambedkar Nagar",
    "Amethi (Chatrapati Sahuji Mahraj Nagar)",
    "Amroha (J.P. Nagar)",
    "Auraiya",
    "Azamgarh",
    "Baghpat",
    "Bahraich",
    "Ballia",
    "Balrampur",
    "Banda",
    "Barabanki",
    "Bareilly",
    "Basti",
    "Bhadohi",
    "Bijnor",
    "Budaun",
    "Bulandshahr",
    "Chandauli",
    "Chitrakoot",
    "Deoria",
    "Etah",
    "Etawah",
    "Faizabad",
    "Farrukhabad",
    "Fatehpur",
    "Firozabad",
    "Gautam Buddha Nagar",
    "Ghaziabad",
    "Ghazipur",
    "Gonda",
    "Gorakhpur",
    "Hamirpur",
    "Hapur (Panchsheel Nagar)",
    "Hardoi",
    "Hathras",
    "Jalaun",
    "Jaunpur",
    "Jhansi",
    "Kannauj",
    "Kanpur Dehat",
    "Kanpur Nagar",
    "Kanshiram Nagar (Kasganj)",
    "Kaushambi",
    "Kushinagar (Padrauna)",
    "Lakhimpur - Kheri",
    "Lalitpur",
    "Lucknow",
    "Maharajganj",
    "Mahoba",
    "Mainpuri",
    "Mathura",
    "Mau",
    "Meerut",
    "Mirzapur",
    "Moradabad",
    "Muzaffarnagar",
    "Pilibhit",
    "Pratapgarh",
    "RaeBareli",
    "Rampur",
    "Saharanpur",
    "Sambhal (Bhim Nagar)",
    "Sant Kabir Nagar",
    "Shahjahanpur",
    "Shamali (Prabuddh Nagar)",
    "Shravasti",
    "Siddharth Nagar",
    "Sitapur",
    "Sonbhadra",
    "Sultanpur",
    "Unnao",
    "Varanasi"
  ],
  "West Bengal":[
    "Alipurduar",
    "Bankura",
    "Birbhum",
    "Burdwan (Bardhaman)",
    "Cooch Behar",
    "Dakshin Dinajpur (South Dinajpur)",
    "Darjeeling",
    "Hooghly",
    "Howrah",
    "Jalpaiguri",
    "Kalimpong",
    "Kolkata",
    "Malda",
    "Murshidabad",
    "Nadia",
    "North 24 Parganas",
    "Paschim Medinipur (West Medinipur)",
    "Purba Medinipur (East Medinipur)",
    "Purulia",
    "South 24 Parganas",
    "Uttar Dinajpur (North Dinajpur)"
  ],
};

List states = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  'Dadra and Nagar Haveli (UT)',
  "Daman and Diu (UT)",
  "Chandigarh (UT)",
  "Chhattisgarh",
  "Delhi (NCT)",
  'Goa',
  "Gujarat",
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  "Karnataka",
  "Kerala",
  'Lakshadweep (UT)',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Puducherry (UT)',
  'Punjab',
  "Telangana",
  'Tamil Nadu',
  'Tripura',
  'Rajasthan',
  'Sikkim',
  'Uttarakhand',
  'Uttar Pradesh',
  'West Bengal',
];

List partsList = [
  {
    "Name": "Washington 4C4",
    "Collection": "Loose Furniture",
    "Type": "STATIONARY SOFAS",
    "Price": "₹980,000"
  },
  {
    "Name": "Edison",
    "Collection": "Loose Furniture",
    "Type": "STATIONARY SOFAS",
    "Price": "₹890,000"
  },
  {
    "Name": "Grand Derby",
    "Collection": "Loose Furniture",
    "Type": "STATIONARY SOFAS",
    "Price": "₹660,000"
  },
  {
    "Name": "Discovery",
    "Collection": "Loose Furniture",
    "Type": "STATIONARY SOFAS",
    "Price": "₹970,000"
  },
  {
    "Name": "Morgan",
    "Collection": "Loose Furniture",
    "Type": "STATIONARY SOFAS",
    "Price": "₹800,000"
  },
  {
    "Name": "Jade Sofa",
    "Collection": "Loose Furniture",
    "Type": "STATIONARY SOFAS",
    "Price": "₹750,000"
  },
  {
    "Name": "Oasis",
    "Collection": "Loose Furniture",
    "Type": "STATIONARY SOFAS",
    "Price": "₹710,000"
  },
  {
    "Name": "Dreamliner",
    "Collection": "Loose Furniture",
    "Type": "STATIONARY SOFAS",
    "Price": "₹920,000"
  },
  {
    "Name": "Nica Daybed",
    "Collection": "Loose Furniture",
    "Type": "STATIONARY SOFAS",
    "Price": "₹930,000"
  },
  {
    "Name": "Startrek",
    "Collection": "Loose Furniture",
    "Type": "STATIONARY SOFAS",
    "Price": "₹770,000"
  },
  {
    "Name": "Valentino",
    "Collection": "Loose Furniture",
    "Type": "Motion Sofas",
    "Price": "₹600,000"
  },
  {
    "Name": "Contrail",
    "Collection": "Loose Furniture",
    "Type": "Motion Sofas",
    "Price": "₹890,000"
  },
  {
    "Name": "Stratus",
    "Collection": "Loose Furniture",
    "Type": "Motion Sofas",
    "Price": "₹840,000"
  },
  {
    "Name": "Evita",
    "Collection": "Loose Furniture",
    "Type": "Motion Sofas",
    "Price": "₹550,000"
  },
  {
    "Name": "Eva",
    "Collection": "Loose Furniture",
    "Type": "Motion Sofas",
    "Price": "₹820,000"
  },
  {
    "Name": "Castro",
    "Collection": "Loose Furniture",
    "Type": "Motion Sofas",
    "Price": "₹720,000"
  },
  {
    "Name": "Nuvola",
    "Collection": "Loose Furniture",
    "Type": "Motion Sofas",
    "Price": "₹950,000"
  },
  {
    "Name": "Eva 3 Seater Daybed",
    "Collection": "Loose Furniture",
    "Type": "Motion Sofas",
    "Price": "₹870,000"
  },
  {
    "Name": "Cirrus",
    "Collection": "Loose Furniture",
    "Type": "Motion Sofas",
    "Price": "₹960,000"
  },
  {
    "Name": "Eva U-Corner",
    "Collection": "Loose Furniture",
    "Type": "Motion Sofas",
    "Price": "₹610,000"
  },
  {
    "Name": "Nimbus Home Theatre",
    "Collection": "Loose Furniture",
    "Type": "Home Theater",
    "Price": "₹730,000"
  },
  {
    "Name": "Cirrus Curve",
    "Collection": "Loose Furniture",
    "Type": "Home Theater",
    "Price": "₹940,000"
  },
  {
    "Name": "Cirrus Straight",
    "Collection": "Loose Furniture",
    "Type": "Home Theater",
    "Price": "₹820,000"
  },
  {
    "Name": "Bellagio ",
    "Collection": "Loose Furniture",
    "Type": "Sofa Cum Bed",
    "Price": "₹830,000"
  },
  {
    "Name": "Conarad",
    "Collection": "Loose Furniture",
    "Type": "Sofa Cum Bed",
    "Price": "₹630,000"
  },
  {
    "Name": "Hilton",
    "Collection": "Loose Furniture",
    "Type": "Sofa Cum Bed",
    "Price": "₹670,000"
  },
  {
    "Name": "Jade",
    "Collection": "Loose Furniture",
    "Type": "ArmChair & Puffee",
    "Price": "₹720,000"
  },
  {
    "Name": "Joy",
    "Collection": "Loose Furniture",
    "Type": "ArmChair & Puffee",
    "Price": "₹980,000"
  },
  {
    "Name": "Pecard",
    "Collection": "Loose Furniture",
    "Type": "ArmChair & Puffee",
    "Price": "₹890,000"
  },
  {
    "Name": "Candy Store",
    "Collection": "Loose Furniture",
    "Type": "ArmChair & Puffee",
    "Price": "₹680,000"
  },
  {
    "Name": "Enigma",
    "Collection": "Loose Furniture",
    "Type": "ArmChair & Puffee",
    "Price": "₹700,000"
  },
  {
    "Name": "Princeton ",
    "Collection": "Loose Furniture",
    "Type": "ArmChair & Puffee",
    "Price": "₹560,000"
  },
  {
    "Name": "Teddy",
    "Collection": "Loose Furniture",
    "Type": "ArmChair & Puffee",
    "Price": "₹610,000"
  },
  {
    "Name": "Yale",
    "Collection": "Loose Furniture",
    "Type": "ArmChair & Puffee",
    "Price": "₹900,000"
  },
  {
    "Name": "Jade Senior",
    "Collection": "Loose Furniture",
    "Type": "ArmChair & Puffee",
    "Price": "₹780,000"
  },
  {
    "Name": "Cocoon",
    "Collection": "Loose Furniture",
    "Type": "ArmChair & Puffee",
    "Price": "₹820,000"
  },
  {
    "Name": "L Shape Kitchen",
    "Collection": "Fixed Furniture",
    "Type": "Kitchens",
    "Price": "₹970,000"
  },
  {
    "Name": "U Shape Kitchen",
    "Collection": "Fixed Furniture",
    "Type": "Kitchens",
    "Price": "₹780,000"
  },
  {
    "Name": "Parallel Kitchen",
    "Collection": "Fixed Furniture",
    "Type": "Kitchens",
    "Price": "₹870,000"
  },
  {
    "Name": "Island Kitchen",
    "Collection": "Fixed Furniture",
    "Type": "Kitchens",
    "Price": "₹940,000"
  },
  {
    "Name": "Straight Line Kitchen",
    "Collection": "Fixed Furniture",
    "Type": "Kitchens",
    "Price": "₹870,000"
  },
  {
    "Name": "Sliding Wardrobe",
    "Collection": "Fixed Furniture",
    "Type": "Wardrobes",
    "Price": "₹920,000"
  },
  {
    "Name": "Hinged Wardrobe",
    "Collection": "Fixed Furniture",
    "Type": "Wardrobes",
    "Price": "₹880,000"
  },
  {
    "Name": "Vanity Unit",
    "Collection": "Fixed Furniture",
    "Type": "Living,Dinning and Orher Units",
    "Price": "₹960,000"
  },
  {
    "Name": "Laundry Unit",
    "Collection": "Fixed Furniture",
    "Type": "Living,Dinning and Orher Units",
    "Price": "₹750,000"
  },
  {
    "Name": "Pooja Unit",
    "Collection": "Fixed Furniture",
    "Type": "Living,Dinning and Orher Units",
    "Price": "₹930,000"
  },
  {
    "Name": "Crockery Unit",
    "Collection": "Fixed Furniture",
    "Type": "Living,Dinning and Orher Units",
    "Price": "₹700,000"
  },
  {
    "Name": "Dresser",
    "Collection": "Fixed Furniture",
    "Type": "Living,Dinning and Orher Units",
    "Price": "₹840,000"
  },
  {
    "Name": "Shoe Unit",
    "Collection": "Fixed Furniture",
    "Type": "Living,Dinning and Orher Units",
    "Price": "₹670,000"
  },
  {
    "Name": "Newcastle",
    "Collection": "Home ccessories",
    "Type": "Center Table",
    "Price": "₹990,000"
  },
  {
    "Name": "Lotus Buds",
    "Collection": "Home ccessories",
    "Type": "Center Table",
    "Price": "₹830,000"
  },
  {
    "Name": "Pretty Pumpkin",
    "Collection": "Home ccessories",
    "Type": "Center Table",
    "Price": "₹990,000"
  },
  {
    "Name": "Merry Go Round",
    "Collection": "Home ccessories",
    "Type": "Center Table",
    "Price": "₹830,000"
  },
  {
    "Name": "Over Hang",
    "Collection": "Home ccessories",
    "Type": "Center Table",
    "Price": "₹980,001"
  },
  {
    "Name": "Sure Footed",
    "Collection": "Home ccessories",
    "Type": "Center Table",
    "Price": "₹890,001"
  },
  {
    "Name": "Meeting Point",
    "Collection": "Home ccessories",
    "Type": "Center Table",
    "Price": "₹660,001"
  },
  {
    "Name": "Fleet Foot",
    "Collection": "Home ccessories",
    "Type": "Center Table",
    "Price": "₹970,001"
  },
  {
    "Name": "Casaviva CT",
    "Collection": "Home ccessories",
    "Type": "Center Table",
    "Price": "₹800,001"
  },
  {
    "Name": "Rubik Cube",
    "Collection": "Home ccessories",
    "Type": "Center Table",
    "Price": "₹750,001"
  },
  {
    "Name": "Snow Flakes",
    "Collection": "Home ccessories",
    "Type": "Cushions",
    "Price": "₹710,001"
  },
  {
    "Name": "Fine Gentlemen",
    "Collection": "Home ccessories",
    "Type": "Cushions",
    "Price": "₹920,001"
  },
  {
    "Name": "Straight Forward",
    "Collection": "Home ccessories",
    "Type": "Cushions",
    "Price": "₹930,001"
  },
  {
    "Name": "Post Bag",
    "Collection": "Home ccessories",
    "Type": "Cushions",
    "Price": "₹770,001"
  },
  {
    "Name": "Prism Rush",
    "Collection": "Home ccessories",
    "Type": "Cushions",
    "Price": "₹600,001"
  },
  {
    "Name": "Barn Rarks",
    "Collection": "Home ccessories",
    "Type": "Cushions",
    "Price": "₹890,001"
  },
  {
    "Name": "Desert Rose",
    "Collection": "Home ccessories",
    "Type": "Cushions",
    "Price": "₹840,001"
  },
  {
    "Name": "Forest Flame",
    "Collection": "Home ccessories",
    "Type": "Cushions",
    "Price": "₹550,001"
  },
  {
    "Name": "Deep Roots",
    "Collection": "Home ccessories",
    "Type": "Cushions",
    "Price": "₹820,001"
  }
];